name: Flutter Build iOS

on: workflow_dispatch

env:
  flutter_version: '3.24.2'

jobs:
  build_ios:
    runs-on: macos-14 # macos-latest is macos-12 actually, and iOS 17+ SDK not supported
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          cache-dependency-path: tools/pnpm-lock.yaml

      - name: Pnpm install
        run: |
          cd tools && pnpm i && cd ..

      - name: Change version info
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          node tools/increment-build-number.mjs ${{ github.server_url }} ${{ github.repository }} ${{ github.run_id }} ${{ github.run_attempt }}

      - name: Change Develop to Distribution
        run: |
          node tools/to-distro.mjs

      - name: Install Apple Certificate
        uses: apple-actions/import-codesign-certs@v3
        with:
          p12-file-base64: ${{ secrets.P12_BASE64 }}
          p12-password: ${{ secrets.P12_PASSWORD }}

      - name: Install the provisioning profile
        env:
          PROVISIONING_CERTIFICATE_BASE64: ${{ secrets.PROVISIONING_PROFILE_BASE64 }}
        run: |
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision

          echo -n "$PROVISIONING_CERTIFICATE_BASE64" | base64 --decode --output $PP_PATH

          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter_version }}
          channel: stable
          cache: true

      - name: Setup Flutter
        run: |
          flutter config --no-cli-animations

      - name: Build iOS
        run: |
          flutter build ios --release --no-codesign

      - name: Build resolve Swift dependencies
        run: |
          xcodebuild -resolvePackageDependencies -workspace ios/Runner.xcworkspace -scheme Runner -configuration Release

      - name: Build xArchive
        run: |
          xcodebuild -workspace ios/Runner.xcworkspace -scheme Runner -configuration Release DEVELOPMENT_TEAM="TGBYYVM7AB" -sdk 'iphoneos' -destination 'generic/platform=iOS' -archivePath build-output/app.xcarchive PROVISIONING_PROFILE="535be9d5-550e-4871-bc9b-c2bdf9728641" clean archive CODE_SIGN_IDENTITY="Apple Distribution: Shanghai Plum Technology Ltd. (TGBYYVM7AB)"

      - name: Export ipa
        run: |
          xcodebuild -exportArchive -archivePath build-output/app.xcarchive -exportPath build-output/ios -exportOptionsPlist ios/ExportOptions.plist

      - name: Get Git info
        id: get_git_info
        run: |
          git fetch --tags
          echo "LATEST_VERSION="$(git tag --sort=-creatordate | head -n 1) >> "$GITHUB_ENV"

      - name: Rename ipa file
        run: |
          mkdir -p build/upload-artifacts/
          mv build-output/ios/life.mysit.SITLife.ipa build/upload-artifacts/sitlife-${{ env.LATEST_VERSION }}.ipa

      - name: Publish iOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sitlife-iOS-release
          path: build/upload-artifacts/sitlife-${{ env.LATEST_VERSION }}.ipa
