name: Building Test

on:
  - pull_request

env:
  flutter_version: '3.24.1'

jobs:
  build_android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter_version }}
          channel: stable
          cache: true

      - name: Setup Flutter
        run: |
          flutter config --no-cli-animations

      - name: Build APK
        run: |
          flutter build apk --target-platform android-arm64,android-arm

      - name: Upload Android Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sitlife-Android-test
          path: build/app/outputs/flutter-apk/
