name: Flutter Build

on:
  workflow_dispatch:
    inputs:
      deploy_app_store:
        description: 'Deploy on App Store connect'
        required: true
        default: true
        type: boolean

permissions: write-all

jobs:
  build_android:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v4
        with:
          repository: plum-tech/mimir-x
          token: ${{ secrets.MIMIR_GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          cache-dependency-path: tools/pnpm-lock.yaml

      - name: Pnpm install
        run: |
          cd tools && pnpm i && pnpm build && cd ..

      - name: Change version
        run: |
          pnpm run increment-build-number

      - name: Install JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          flutter-version-file: pubspec.yaml

      - name: Build APK
        run: |
          flutter config --no-cli-animations
          flutter build apk --release --target-platform android-arm,android-arm64

      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        id: sign_apk
        with:
          releaseDirectory: build/app/outputs/flutter-apk
          signingKeyBase64: ${{ secrets.APK_SIGN_JKS_BASE64 }}
          keyStorePassword: ${{ secrets.APK_SIGN_JKS_PASSWORD }}
          keyPassword: ${{ secrets.APK_SIGN_ALIAS_PASS }}
          alias: ${{ secrets.APK_SIGN_ALIAS }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Publish Android Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Android-release
          path: build/app/outputs/flutter-apk/*-signed.apk

  build_ios:
    runs-on: macos-15
    if: github.ref == 'refs/heads/master' && ${{ inputs.deploy_app_store }}

    steps:
      - uses: actions/checkout@v4
        with:
          repository: plum-tech/mimir-x
          token: ${{ secrets.MIMIR_GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          cache-dependency-path: tools/pnpm-lock.yaml

      - name: Pnpm install
        run: |
          cd tools && pnpm i && pnpm build && cd ..

      - name: Change version
        run: |
          pnpm run increment-build-number

      - name: Change Develop to Distribution
        run: |
          pnpm run to-distro

      - name: Install Apple Certificate
        uses: apple-actions/import-codesign-certs@v3
        with:
          p12-file-base64: ${{ secrets.P12_BASE64 }}
          p12-password: ${{ secrets.P12_PASSWORD }}

      - name: Install the provisioning profile
        env:
          PROVISIONING_CERTIFICATE_BASE64: ${{ secrets.PROVISIONING_PROFILE_BASE64 }}
        run: |
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision

          echo -n "$PROVISIONING_CERTIFICATE_BASE64" | base64 --decode --output $PP_PATH

          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          flutter-version-file: pubspec.yaml

      - name: Build iOS
        run: |
          flutter config --no-cli-animations
          flutter build ios --release --no-codesign

      - name: Build resolve Swift dependencies
        run: |
          xcodebuild -resolvePackageDependencies -workspace ios/Runner.xcworkspace -scheme Runner -configuration Release

      - name: Build xArchive
        run: |
          xcodebuild -workspace ios/Runner.xcworkspace -scheme Runner -configuration Release DEVELOPMENT_TEAM="TGBYYVM7AB" -sdk 'iphoneos' -destination 'generic/platform=iOS' -archivePath build-output/app.xcarchive PROVISIONING_PROFILE="535be9d5-550e-4871-bc9b-c2bdf9728641" clean archive CODE_SIGN_IDENTITY="Apple Distribution: Shanghai Plum Technology Ltd. (TGBYYVM7AB)"

      - name: Export ipa
        run: |
          xcodebuild -exportArchive -archivePath build-output/app.xcarchive -exportPath build-output/ios -exportOptionsPlist ios/ExportOptions.plist

      - name: Publish iOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: iOS-release
          path: build-output/ios/life.mysit.SITLife.ipa

  after_build:
    runs-on: macos-latest
    needs: [ build_android, build_ios ]
    steps:
      - uses: actions/checkout@v4
        with:
          repository: plum-tech/mimir-x
          token: ${{ secrets.MIMIR_GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          cache-dependency-path: tools/pnpm-lock.yaml

      - name: Pnpm install
        run: |
          cd tools && pnpm i && pnpm build && cd ..

      - name: Change version and commit tag
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          pnpm run increment-build-number --commit

      - name: Get iOS Artifact
        uses: actions/download-artifact@v4
        with:
          name: iOS-release
          path: build/

      - name: Deploy to App Store (TestFlight)
        uses: apple-actions/upload-testflight-build@v1
        with:
          app-path: ${{ github.workspace }}/build/life.mysit.SITLife.ipa
          issuer-id: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          api-key-id: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          api-private-key: ${{ secrets.APP_STORE_CONNECT_API_PRIVATE_KEY }}

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          repository: plum-tech/mimir-x
          github_token: ${{ secrets.MIMIR_GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Get Android Artifact
        uses: actions/download-artifact@v4
        with:
          name: Android-release
          path: build/

      - name: Publish preview version
        continue-on-error: true
        env:
          MIMIR_VERSION_ADMIN_TOKEN: ${{ secrets.MIMIR_VERSION_ADMIN_TOKEN }}
        run: |
          pnpm run publish-preview --upload build/app-release-signed.apk
