name: 2.Draft New Release

on: [ workflow_dispatch ]

permissions:
  contents: write

jobs:
  draft-new-release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          cache-dependency-path: tools/pnpm-lock.yaml

      - name: Pnpm install
        run: |
          cd tools && pnpm i && cd ..

      - name: Draft new release
        if: github.repository == 'liplum-dev/mimir'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          node tools/draft-release.mjs
