name: 3.Release New Version

on:
  release:
    types: [ released ]

permissions:
  contents: read
  packages: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          cache-dependency-path: tools/pnpm-lock.yaml

      - name: Pnpm install
        run: |
          cd tools && pnpm i && cd ..

      - name: Upload artifacts onto SIT-MC sever
        if: github.repository == 'plum-tech/mimir'
        continue-on-error: true
        env:
          SITMC_TEMP_SERVER_AUTH: ${{ secrets.SITMC_TEMP_SERVER_AUTH }}
        run: |
          node tools/upload-release-sitmc.mjs

      - name: Deploy
        if: github.repository == 'plum-tech/mimir'
        env:
          MIMIR_VERSION_TOKEN: ${{ secrets.MIMIR_VERSION_TOKEN }}
        run: |
          node tools/publish-release.mjs

      - name: Notify the latest release
        if: github.repository == 'plum-tech/mimir'
        continue-on-error: true
        env:
          QQBOT_URL: ${{ secrets.gocq_sendgroupmsg_url }}
        run: |
          node tools/bot-notify-release.mjs
