name: Web
on: workflow_dispatch
permissions: write-all

env:
  flutter_version: '3.22.3'

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter_version }}
          channel: stable
          cache: true

      - uses: bluefireteam/flutter-gh-pages@v8
        with:
          baseHref: /mimir/
