name: Windows
on: workflow_dispatch

env:
  flutter_version: '3.24.2'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter_version }}
          channel: stable
          cache: true

      - name: Setup Flutter
        run: |
          flutter config --no-cli-animations

      - name: Build Windows
        run: |
          flutter pub run build_runner build --delete-conflicting-outputs
          dart run msix:create

      - name: Upload building
        uses: actions/upload-artifact@v4
        with:
          name: SITLife-Windows-release
          path: build\windows\x64\runner\Release\SIT-Life.msix
